### ISSUE TITLE
Type Error: an integer is required (got type tuple)

### ISSUE THREAD

**Issue by darkprince1337** [arccoder/opencvdragrect#3]
```
TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)

TypeError: an integer is required (got type tuple)

Traceback (most recent call last):

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 124, in dragrect
    mouseMove(x, y, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 235, in mouseMove
    clearCanvasNDraw(dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 356, in clearCanvasNDraw
    drawSelectMarkers(tmp, dragObj)

  File "/home/anarchaos/Downloads/opencvdragrect/selectinwindow.py", line 394, in drawSelectMarkers
    (0, 255, 0), 2)
```

**Comment by zeynepkoyun** [comment]
The values ​​written in cv2.rectangle in the "drawSelectMarkers" method in the "selectwindow.py" file must be int. @darkprince1337

**Comment by arccoder** [comment]
@darkprince1337, @zeynepkoyun  is correct.
In fact as of commit d56ac9c4ab50ff46ecbac35fd2784f042f3014f1 the issue is resolved.
With a few more updates, a major one been modified the code from Python2 to Python3.
